version: '3'

networks:
  comunikime_net:
    driver: bridge

volumes:
  postgresql:

services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: localhost
    ports:
      - 5432:5432
    networks:
      - comunikime_net
    volumes:
      - postgresql:/var/lib/postgresql

  back:
    image: comunikime
    build: 
      context: back
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    networks:
      - comunikime_net
    depends_on:
      - db
    command: ["npm", "run", "start:dev"]
